owncloud:
  image: kranthitherising/myowncloud
  ports:
   - "9180:80"
  links:
    - db
  environment:
    - OWNCLOUD_ADMIN_USERNAME=admin
    - OWNCLOUD_ADMIN_PASSWORD=admin

db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=password
